### ISSUE TITLE
Overwatch HUD doesn't support latest update

### ISSUE THREAD

**Issue by RoonMoonlight** [nimtra/overwatchhud#4]
Hi, Ah_RoonGaming here.

The hud doesn't support latest version, it keeps reverting to Original HUD.
Can you fix this issue?

Thanks.
![bug_report](https://user-images.githubusercontent.com/25527589/47275867-2dac4f00-d5ee-11e8-805f-564fbc3aa1c1.png)

**Comment by nimtra** [comment]
fixed in latest update
